theme: jekyll-theme-chirpy

lang: zh-CN
timezone: Asia/Shanghai

title: 马斯克铁粉站
tagline: 最大中文马斯克粉丝内容站
description: Elon Musk 深度档案库

url: "https://muskfans.cn"

github:
  username: wsgsc

social:
  name: 马斯克铁粉站
  links: []

avatar: /assets/img/avatar.png

paginate: 10

toc: false

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false

plugins:
  - jekyll-paginate

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      math: false
      mermaid: false
  - scope:
      path: _tabs
    values:
      layout: page
      permalink: /:title/
